package com.cyberdev.covoituragetn;



import com.codename1.components.SpanLabel;
import com.codename1.io.CharArrayReader;
import com.codename1.io.ConnectionRequest;
import com.codename1.io.JSONParser;

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;


import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.l10n.SimpleDateFormat;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.spinner.Picker;
import entity.Alerte;
import java.io.IOException;


import java.util.ArrayList;


import java.util.List;
import java.util.Map;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Alertes {

    private Form current,f2;
    private Resources theme;
    Command cmd1, cmd2,cmd4, cmdBack;
     private ConnectionRequest connectionRequest;
     private SpanLabel sp;
       Alerte a = new Alerte();
     

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
         cmd1 = new Command("Mon profil");
        cmd2 = new Command("Mes alertes");
  
        cmd4 = new Command("Page 4");
        cmdBack = new Command("Back");
   
    }
    
    public void start() {
Form f =new Form("Insert",BoxLayout.y());
f.setUIID("log");
   f2 =new Form("Mes Alertes",BoxLayout.y());
   f2.setUIID("log");
 sp = new SpanLabel();
        f2.add(sp);
   // f.getToolbar().addCommandToSideMenu(cmd1);
      //  f.getToolbar().addCommandToSideMenu(cmd2);
       
        f.getToolbar().addCommandToOverflowMenu(cmd4);
         f.addCommandListener(ev -> {
            if (ev.getCommand() == cmd1) {
             //   f1.show();
            }
            if (ev.getCommand() == cmd2) {
             
                
        ConnectionRequest con = new ConnectionRequest();
        con.setUrl("http://localhost/script_sarra/selectAlerte.php");
        con.addResponseListener(new ActionListener<NetworkEvent>() {

            @Override
            public void actionPerformed(NetworkEvent evt) {
               // getListAlerte(new String(con.getResponseData()));
            // System.out.println(getListAlerte(new String(con.getResponseData())));
             ArrayList<Alerte> al=getListAlerte(new String(con.getResponseData()));
        
           //  for (Alerte liste : al) {

           //   f2.refreshTheme();
           //  }
           }
        });
        NetworkManager.getInstance().addToQueue(con);
                f2.show();
            }
        
        });
        TextField tflieudepart= new TextField("","Lieu depart");
         TextField tflieuarrivee= new TextField("","Lieu arrivee");
         // TextField tfdatedepart= new TextField("","Date depart");
          Picker datePicker = new Picker();
datePicker.setType(Display.PICKER_TYPE_DATE);
SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy/MM/dd");
datePicker.setFormatter(dateFormatter);
          TextField tfheuredepart= new TextField("","Heure depart");
          Button btn= new Button("valider");
          f.add(tflieudepart);
           f.add(tflieuarrivee);
            f.add(datePicker);
            f.add(tfheuredepart);
          f.add(btn);
          f.show();
          btn.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent evt) {
        ConnectionRequest con = new ConnectionRequest();
        con.setUrl("http://localhost/script_sarra/insertAlerte.php?lieudepart="+tflieudepart.getText()+"&lieuarrivee="+tflieuarrivee.getText()+"&date="+datePicker.getText()+"&heure="+tfheuredepart.getText()+"&idUser=3");
        System.out.println(datePicker.getDate());
        
     con.addResponseListener(new ActionListener<NetworkEvent>() {

                    @Override
                    public void actionPerformed(NetworkEvent evt) {
                        
                        byte[] data = (byte[]) evt.getMetaData();
                        String s = new String(data);
                        System.out.println(s);
                        if (s.equals("success")) {
                            Dialog.show("Confirmation", "ajout ok", "Ok", null);
                        } else {
                            Dialog.show("Erreur", "erreur", "Ok", null);
                        }
                    }
                });
        
        NetworkManager.getInstance().addToQueue(con);
    }
});
    }
 public ArrayList<Alerte> getListAlerte(String json) {
        ArrayList<Alerte> listAlertes = new ArrayList<>();
     
        try {
            JSONParser j = new JSONParser();
            Map<String, Object> alertes = j.parseJSON(new CharArrayReader(json.toCharArray()));
   List<Map<String, Object>> list = (List<Map<String, Object>>) alertes.get("alerte");
   
    f2 =new Form("Mes Alertes",BoxLayout.y());
 sp = new SpanLabel();
        f2.add(sp);

              for (Map<String, Object> obj : list) {
              
              

            
                a.setLieuDepart(obj.get("lieudepart").toString());
                
              //  a.setDate((java.sql.Date) obj.get("date"));
                a.setLieuArrivee(obj.get("lieuarrivee").toString());
               a.setHeure(Integer.parseInt(obj.get("heure").toString()));
               
           
             listAlertes.add(a);
             sp.setText(sp.getText()+" "+a.getLieuDepart()+" "+a.getLieuArrivee()+" "+a.getHeure()+" \n");
           


         }
              f2.refreshTheme();
              f2.show();

        } catch (IOException ex) {
         }
          
      return listAlertes;
     

    }
    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
       
    public void destroy() {
    }

}
