package com.cyberdev.covoituragetn;


import com.codename1.io.ConnectionRequest;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.io.NetworkManager;
import com.codename1.ui.Button;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Inscription {

    private Form f;
    private Resources theme;

  
    
    public Inscription(Resources theme) {
        
        f = new Form("Hi World");
        TextField tfNom=new TextField();
        TextField tfprenom=new TextField();
        TextField tfUserName=new TextField();
        TextField tfMail=new TextField();
        TextField tfMdp=new TextField();
        TextField tfRmdp=new TextField();
        Button btnOk =new Button("Valider");
        
        f.add(tfNom);
        f.add(tfprenom);
        f.add(tfUserName);
        f.add(tfMail);
        f.add(tfMdp);
        f.add(tfRmdp);
        f.add(btnOk);
        
        btnOk.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
           ConnectionRequest con = new ConnectionRequest();
           con.setUrl("http://localhost/pi/insert.php?nom=" + tfNom.getText() + "&prenom=" + tfprenom.getText()+ "&username=" 
                   + tfUserName.getText() + "&password=" + tfMdp.getText() + "&email=" + tfMail.getText());
                    Dialog.show("Alert", "Ajout avec Succes", "Ok",null);
            NetworkManager.getInstance().addToQueue(con);
            }
        });
        
        f.show();
    }

  public Form getF() {
        return f;
    }

}
