package com.cyberdev.covoituragetn;

import com.codename1.io.CharArrayReader;
import com.codename1.io.ConnectionRequest;
import com.codename1.io.JSONParser;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.l10n.ParseException;
import com.codename1.ui.Button;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import entity.User;
import java.io.IOException;
import java.util.Map;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class ProfilForm {

    private Form current, f;
    private Resources theme;

    User u = new User(17);

 

    public ProfilForm(Resources theme) {
        
        f = new Form("Hi World");

        ConnectionRequest con = new ConnectionRequest();
        con.setUrl("http://localhost/pi/select.php?id=" + u.getId());

        con.addResponseListener(new ActionListener<NetworkEvent>() {

            @Override
            public void actionPerformed(NetworkEvent evt) {

                User user = getUser(new String(con.getResponseData()));

            }
        });
        NetworkManager.getInstance().addToQueue(con);
        f.show();
    }

    public Form getF() {
        return f;
    }

   

    public User getUser(String json) {

        User user = new User();

        try {
            JSONParser j = new JSONParser();
            Map<String, Object> users = j.parseJSON(new CharArrayReader(json.toCharArray()));
            Map<String, Object> list = (Map<String, Object>) users.get("user");

//            user.setNom(list.get("nom").toString());
//            user.setPrenom(list.get("prenom").toString());
//            user.setLogin(list.get("login").toString());
//            user.setEmail(list.get("email").toString());
user.setNom(LogIn.e.getNom());
user.setPrenom(LogIn.e.getPrenom());
user.setLogin(LogIn.e.getLogin());
user.setEmail(LogIn.e.getEmail());

            Label lnom = new Label(user.getNom());
            Label lPrenom = new Label(user.getPrenom());
            Label lMail = new Label(user.getEmail());
            Label lusername = new Label(user.getLogin());
            
            f.add(lusername);
            f.add(lnom);
            f.add(lPrenom);
            f.add(lMail);
            f.show();

        } catch (IOException ex) {
        }

        return user;

    }

 


}
